/**
 * In-browser filesystem shim for xYang / netlab YANG loading.
 * File map is generated by vite.config.ts into yang-files-data.ts.
 */
import yangFiles from "./yang-files-data";

const files = new Map<string, string>(Object.entries(yangFiles));

function norm(p: string): string {
  return p.replace(/\\/g, "/").replace(/\/+/g, "/");
}

function lookup(p: string): string | undefined {
  const n = norm(p);
  if (files.has(n)) return files.get(n);
  // Tolerate absolute vs relative and basename-only lookups from xYang
  const candidates = [n, n.replace(/^\//, ""), `/yang/${n.split("/").pop()}`, n.split("/").pop() ?? ""];
  for (const c of candidates) {
    if (c && files.has(c)) return files.get(c);
  }
  const base = n.split("/").pop();
  if (!base) return undefined;
  for (const [k, v] of files) {
    if (k.endsWith(`/${base}`) || k === base) return v;
  }
  return undefined;
}

export function readFileSync(p: string, _encoding?: string): string {
  const data = lookup(p);
  if (data === undefined) {
    const err = new Error(
      `ENOENT: no such file or directory, open '${p}' (yang files: ${[...files.keys()].join(", ")})`,
    ) as Error & { code?: string };
    err.code = "ENOENT";
    throw err;
  }
  return data;
}

export function existsSync(p: string): boolean {
  return lookup(p) !== undefined;
}

export function readdirSync(p: string): string[] {
  const prefix = norm(p).replace(/\/$/, "");
  const names = new Set<string>();
  for (const k of files.keys()) {
    const nk = norm(k);
    let rest: string | undefined;
    if (nk.startsWith(prefix + "/")) rest = nk.slice(prefix.length + 1);
    else if ((prefix === "/yang" || prefix === "yang") && nk.startsWith("/yang/")) {
      rest = nk.slice("/yang/".length);
    }
    if (!rest) continue;
    names.add(rest.split("/")[0]!);
  }
  return [...names];
}

export default { readFileSync, existsSync, readdirSync };
