/**
 * In-browser filesystem shim for xYang / netlab YANG loading.
 * File map is generated by vite.config.ts into yang-files-data.ts.
 *
 * Path lookup must not invent files in the wrong directory: a basename
 * fallback that maps `/yang/modules/netlab-topology.yang` →
 * `/yang/netlab-topology.yang` makes xYang cache a duplicate module, so
 * cross-module `augment` mutates the wrong schema and node fields like
 * `bgp` appear as "Unknown field".
 */
import yangFiles from "./yang-files-data";

const files = new Map<string, string>(Object.entries(yangFiles));

function norm(p: string): string {
  return p.replace(/\\/g, "/").replace(/\/+/g, "/");
}

/** True when `p` is a bare filename (optional leading slash only). */
function isBasenameOnly(p: string): boolean {
  const n = norm(p);
  if (!n || n === "/") return false;
  const trimmed = n.startsWith("/") ? n.slice(1) : n;
  return trimmed.length > 0 && !trimmed.includes("/");
}

function lookup(p: string): string | undefined {
  const n = norm(p);
  if (files.has(n)) return files.get(n);
  // Absolute vs relative without inventing a different directory
  if (n.startsWith("/")) {
    const rel = n.slice(1);
    if (files.has(rel)) return files.get(rel);
  } else if (files.has(`/${n}`)) {
    return files.get(`/${n}`);
  }

  // Basename-only: tolerate xYang lookups that omit the directory
  if (isBasenameOnly(n)) {
    const base = n.replace(/^\//, "");
    for (const [k, v] of files) {
      if (k.endsWith(`/${base}`) || k === base) return v;
    }
  }
  return undefined;
}

export function readFileSync(p: string, _encoding?: string): string {
  const data = lookup(p);
  if (data === undefined) {
    const err = new Error(
      `ENOENT: no such file or directory, open '${p}' (yang files: ${[...files.keys()].join(", ")})`,
    ) as Error & { code?: string };
    err.code = "ENOENT";
    throw err;
  }
  return data;
}

export function existsSync(p: string): boolean {
  return lookup(p) !== undefined;
}

export function readdirSync(p: string): string[] {
  const prefix = norm(p).replace(/\/$/, "");
  const names = new Set<string>();
  for (const k of files.keys()) {
    const nk = norm(k);
    let rest: string | undefined;
    if (nk.startsWith(prefix + "/")) rest = nk.slice(prefix.length + 1);
    else if ((prefix === "/yang" || prefix === "yang") && nk.startsWith("/yang/")) {
      rest = nk.slice("/yang/".length);
    }
    if (!rest) continue;
    names.add(rest.split("/")[0]!);
  }
  return [...names];
}

export default { readFileSync, existsSync, readdirSync };
