import { defineConfig } from "vite";
import fs from "node:fs";
import path from "node:path";

// GitHub project pages serve from /<repo>/ when publishing the /docs folder.
const base = process.env.VITE_BASE_PATH || "/";
const buildTime = new Date().toISOString();
const shim = (name: string) => path.resolve(__dirname, `src/${name}`);
const yangRoot = path.resolve(__dirname, "../../yang");
const yangDataFile = path.resolve(__dirname, "src/yang-files-data.ts");

function collectYangFiles(): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (dir: string): void => {
    if (!fs.existsSync(dir)) return;
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        walk(full);
        continue;
      }
      if (!ent.name.endsWith(".yang")) continue;
      const rel = path.relative(yangRoot, full).split(path.sep).join("/");
      const text = fs.readFileSync(full, "utf8");
      out[`/yang/${rel}`] = text;
      out[`yang/${rel}`] = text;
    }
  };
  walk(yangRoot);
  return out;
}

/** Concrete module (not virtual) so esbuild dep optimization can resolve it. */
function writeYangFilesData(): void {
  const body =
    `/** Auto-generated by vite.config.ts — do not edit. */\n` +
    `const yangFiles: Record<string, string> = ${JSON.stringify(collectYangFiles())};\n` +
    `export default yangFiles;\n`;
  fs.writeFileSync(yangDataFile, body);
}

writeYangFilesData();

export default defineConfig({
  root: ".",
  base,
  define: {
    __BUILD_TIME__: JSON.stringify(buildTime),
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
  resolve: {
    alias: [
      {
        find: "@exergy-connect/netlab",
        replacement: path.resolve(__dirname, "../../packages/core/src/browser.ts"),
      },
      // Let xYang / schema load yang/ in the browser
      { find: /^node:fs$/, replacement: shim("yang-fs-shim.ts") },
      { find: /^fs$/, replacement: shim("yang-fs-shim.ts") },
      { find: /^node:path$/, replacement: shim("yang-path-shim.ts") },
      { find: /^path$/, replacement: shim("yang-path-shim.ts") },
      { find: /^node:url$/, replacement: shim("yang-url-shim.ts") },
      { find: /^url$/, replacement: shim("yang-url-shim.ts") },
    ],
  },
  server: {
    fs: {
      allow: [path.resolve(__dirname, "../.."), path.resolve(__dirname, "../../../xYang")],
    },
  },
});
